name: Build
on:
  push:
    branches: [ main ]  
  workflow_dispatch:
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install pyinstaller
      - run: pip install pyqt6
      - run: pip install minecraft-launcher-lib
      - run: pyinstaller --name netherfall-launcher --windowed --onefile main.py
      - uses: actions/upload-artifact@v4
        with:
          name: netherfall-launcher-linux
          path: dist/main

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install pyinstaller
      - run: pip install pyqt6
      - run: pip install minecraft-launcher-lib
      - run: pyinstaller --name netherfall-launcher --windowed --onefile main.py
      - uses: actions/upload-artifact@v4
        with:
          name: netherfall-launcher-windows
          path: dist/main.exe
